### ISSUE TITLE
No errors occur, but no executables are generated

### ISSUE THREAD

**Issue by WANGYINGYU** [HorizonAD/stereo_dso#10]
Hello,
When I make the program no errors occure,but no executables are generated,how can I solve this problem?
Thanks.

**Comment by WANGYINGYU** [comment]
![1](https://user-images.githubusercontent.com/31499655/42930203-f47f9a08-8b6e-11e8-9b4d-3ee870bf326a.png)

**Comment by JiatianWu** [comment]
It is under /build/bin.

**Comment by WANGYINGYU** [comment]
Thank you.
