### ISSUE TITLE
For god's sake, what's wrong with your code?

### ISSUE THREAD

**Issue by ProstoNekitos** [HorizonAD/stereo_dso#22]
I mean look at: 
https://github.com/HorizonAD/stereo_dso/blob/master/src/FullSystem/FullSystem.cpp#L945
As well as many memory leaks and conditions before delete()

Algorithm is quite good, but somebody should refactor you code
Are you still alive? Would you merge a fork with refactored code if i make one?

**Comment by ProstoNekitos** [comment]
Btw check those guys fork. They did a lot 
https://github.com/maximosipov/stereo_dso

**Comment by JiatianWu** [comment]
This repo is a rough implementation and was released to give a solution about how to do stereo dso. Everyone is welcomed to do development/refactor based on this. So yeah you can push your patches so I can review/merge it.

**Comment by ProstoNekitos** [comment]
@JiatianWu sorry for being emotional, i was debugging it for quite a while and got really tired
But thanks for your response, i'll made pull request as soon as l'll have spare time

**Comment by ProstoNekitos** [comment]
@JiatianWu btw can you pls explain what is going on there https://github.com/HorizonAD/stereo_dso/blob/master/src/FullSystem/FullSystem.cpp#L945
Especially how this one `newpoint != (PointHessian*)((long)(-1))` works

**Comment by JiatianWu** [comment]
> @JiatianWu btw can you pls explain what is going on there https://github.com/HorizonAD/stereo_dso/blob/master/src/FullSystem/FullSystem.cpp#L945
> Especially how this one `newpoint != (PointHessian*)((long)(-1))` works

That comes from original dso code. Ask under dso repo's issue would be better for you.
