### ISSUE TITLE
make instead of make -j

### ISSUE THREAD

**Issue by hanyang1986** [HorizonAD/stereo_dso#4]
I found that I tried to build the binary file with make -j  but it failed. I think if someone, who also meets the same error, can try to use make.

Btw, the calibration file of kitti dataset names calib.txt. I have no idea, why it can not be read by binary file. I'm not sure if it is my problem. 

And thank you so much for your sharing.

**Comment by JiatianWu** [comment]
Could you be more specific about how it fails?

**Comment by hanyang1986** [comment]
Probably the reason is the old cpu can not build binary files with multi-thread.
