### ISSUE TITLE
Seg fault when running KITTI sequences

### ISSUE THREAD

**Issue by nikoImagry** [HorizonAD/stereo_dso#6]
When I try running for a KITTI sequence, using the minimal run command in the README, I get the following output:

> loading data from /media/nikolai/DATA/KITTI_gray/dataset/sequences/01!
> loading calibration from calibs/KITTI_00-03.txt!
> 
> =============== PRESET Settings: ===============
> DEFAULT settings:
> - no  real-time enforcing
> - 2000 active points
> - 5-7 active frames
> - 1-6 LM iteration each KF
> - original image resolution
> ==============================================
> PHOTOMETRIC MODE WITHOUT CALIBRATION!
> Reading Calibration from file calibs/KITTI_00-03.txt ... found!
> Input resolution: 1241 376
> In: 718.856000 718.856000 607.192800 185.215700 0.000000
> Out: No Rectification
> Output resolution: 1241 376
> Baseline: 0.537000 
> 
> Rectified Kamera Matrix:
> 718.856       0 607.193
>       0 718.856 185.216
>       0       0       1
> 
> NO PHOTOMETRIC Calibration!
> Reading Photometric Calibration from file 
> PhotometricUndistorter: Could not open file!
> set EXPOSURES to zero!
> got 1101 images and 1101 timestamps and 0 exposures.!
> ImageFolderReader: got 1101 files in /media/nikolai/DATA/KITTI_gray/dataset/sequences/01/image_0!
> Reading Calibration from file calibs/KITTI_00-03.txt ... found!
> Input resolution: 1241 376
> In: 718.856000 718.856000 607.192800 185.215700 0.000000
> Out: No Rectification
> Output resolution: 1241 376
> Baseline: 0.537000 
> 
> Rectified Kamera Matrix:
> 718.856       0 607.193
>       0 718.856 185.216
>       0       0       1
> 
> NO PHOTOMETRIC Calibration!
> Reading Photometric Calibration from file 
> PhotometricUndistorter: Could not open file!
> set EXPOSURES to zero!
> got 1101 images and 1101 timestamps and 0 exposures.!
> ImageFolderReader: got 1101 files in /media/nikolai/DATA/KITTI_gray/dataset/sequences/01/image_1!
> using pyramid levels 0 to 0. coarsest resolution: 1241 x 376!
> 
> 
> ===============WARNING!===================
>  using not enough pyramid levels.
> Consider scaling to a resolution that is a multiple of a power of 2.
> 
> 
> ===============WARNING!===================
>  I need higher resolution.
> I will probably segfault.
> using pyramid levels 0 to 0. coarsest resolution: 1241 x 376!
> 
> 
> ===============WARNING!===================
>  using not enough pyramid levels.
> Consider scaling to a resolution that is a multiple of a power of 2.
> 
> 
> ===============WARNING!===================
>  I need higher resolution.
> I will probably segfault.
> START PANGOLIN!
> Segmentation fault (core dumped)
> 

I tried rescaling the resolutions to a multiples of powers of 2, but got the same result.
Am I missing something here?

The command I used : 
bin/dso_dataset files=/path/KITTI_gray/dataset/sequences/01 calib=path_to_calib/KITTI_00-03.txt preset=0 mode=1

My calibration file is 
Pinhole 718.856 718.856 607.1928 185.2157 0
1241 376
none
1241 376
0.537

Thanks

**Comment by JiatianWu** [comment]
For the rectified size parameters, please try numbers that are 2 the power of n. 512 256 would be a reasonable choice.

**Comment by ouerkakaChango** [comment]
I managed to run the program use this for 00:
718.856	718.856	607.1928 185.2157 0
1241 376
crop
640 480
0.3861448
(Without 'Pinhole',the output changes)

**Comment by leonardohaig** [comment]
I have the same problem as @nikoImagry nikoImagry，have you solved it? thanks
