### ISSUE TITLE
Running Kitti dataset 05-11 with Segmentation fault

### ISSUE THREAD

**Issue by hanyang1986** [HorizonAD/stereo_dso#8]
I tried to run kitti dataset from 05 to 11 with calibration file like this:
707.0912 707.0912 601.8873 183.1104 0.000000 0.000000 0.000000 0.000000
1241 376
crop
960 288
0.1
but I met a Segmentation  fault.

> =============== PRESET Settings: ===============
> DEFAULT settings:
> - no  real-time enforcing
> - 2000 active 
> Rectified Kamera Matrix:
> 546.916       0   465.5
>       0 541.346 140.144
>       0       0       1
> 
> NO PHOTOMETRIC Calibration!
> Reading Photometric Calibration from file 
> PhotometricUndistorter: Could not open file!
> set EXPOSURES to zero!
> got 921 images and 921 timestamps and 0 exposures.!
> ImageFolderReader: got 921 files in /media/alex/589EA5189EA4F024/dataset/sequences/11/image_1!
> using pyramid levels 0 to 3. coarsest resolution: 120 x 36!
> using pyramid levels 0 to 3. coarsest resolution: 120 x 36!
> START PANGOLIN!
> Segmentation faultpoints
> - 5-7 active frames
> - 1-6 LM iteration each KF
> - original image resolution
> ==============================================
> PHOTOMETRIC MODE WITHOUT CALIBRATION!
> Reading Calibration from file /media/alex/589EA5189EA4F024/dataset/sequences/11/camera.txt ... found!
> found RadTan (OpenCV) camera model, building rectifier.
> Creating RadTan undistorter
> Input resolution: 1241 376
> In: 707.091200 707.091200 601.887300 183.110400 0.000000 0.000000 0.000000 0.000000
> Out: Rectify Crop
> Output resolution: 960 288
> Baseline: 0.100000 
> finding CROP optimal new model!
> initial range: x: -0.8597 - 0.9114; y: -0.2615 - 0.2740!
> iteration 00001: range: x: -0.8554 - 0.9069; y: -0.2615 - 0.2740!
> iteration 00002: range: x: -0.8511 - 0.9023; y: -0.2615 - 0.2740!
> iteration 00003: range: x: -0.8511 - 0.9023; y: -0.2602 - 0.2726!
> iteration 00004: range: x: -0.8511 - 0.9023; y: -0.2589 - 0.2713!
> iteration 00005: range: x: -0.8511 - 0.9023; y: -0.2589 - 0.2713!
> 
> Rectified Kamera Matrix:
> 546.916       0   465.5
>       0 541.346 140.144
>       0       0       1
> 
> NO PHOTOMETRIC Calibration!
> Reading Photometric Calibration from file 
> PhotometricUndistorter: Could not open file!
> set EXPOSURES to zero!
> got 921 images and 921 timestamps and 0 exposures.!
> ImageFolderReader: got 921 files in /media/alex/589EA5189EA4F024/dataset/sequences/11/image_0!
> Reading Calibration from file /media/alex/589EA5189EA4F024/dataset/sequences/11/camera.txt ... found!
> found RadTan (OpenCV) camera model, building rectifier.
> Creating RadTan undistorter
> Input resolution: 1241 376
> In: 707.091200 707.091200 601.887300 183.110400 0.000000 0.000000 0.000000 0.000000
> Out: Rectify Crop
> Output resolution: 960 288
> Baseline: 0.100000 
> finding CROP optimal new model!
> initial range: x: -0.8597 - 0.9114; y: -0.2615 - 0.2740!
> iteration 00001: range: x: -0.8554 - 0.9069; y: -0.2615 - 0.2740!
> iteration 00002: range: x: -0.8511 - 0.9023; y: -0.2615 - 0.2740!
> iteration 00003: range: x: -0.8511 - 0.9023; y: -0.2602 - 0.2726!
> iteration 00004: range: x: -0.8511 - 0.9023; y: -0.2589 - 0.2713!
> iteration 00005: range: x: -0.8511 - 0.9023; y: -0.2589 - 0.2713!
> 
> Rectified Kamera Matrix:
> 546.916       0   465.5
>       0 541.346 140.144
>       0       0       1
> 
> NO PHOTOMETRIC Calibration!
> Reading Photometric Calibration from file 
> PhotometricUndistorter: Could not open file!
> set EXPOSURES to zero!
> got 921 images and 921 timestamps and 0 exposures.!
> ImageFolderReader: got 921 files in /media/alex/589EA5189EA4F024/dataset/sequences/11/image_1!
> using pyramid levels 0 to 3. coarsest resolution: 120 x 36!
> using pyramid levels 0 to 3. coarsest resolution: 120 x 36!
> START PANGOLIN!
> Segmentation fault

but the sequences 00 and 01 have pretty good  performances. I tried to modify the calibration file but problem is still there. I guess the problem is due to main_dso_pangolin.cpp.

Can you do me a favor to figure out the problem? Thanks.

**Comment by LinHuican** [comment]
Hi. 
I have the same problem, do you solve it and how?

**Comment by JiatianWu** [comment]
Maybe change you crop size to 2^n.
